name: Deploy to Google Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Build app
        run: npm run build

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: valeford-app  # ggf. anpassen
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true

      - name: Build & push Docker image
        run: |
          gcloud builds submit --tag gcr.io/valeford-app/valeford-web

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy valeford-web \
            --image gcr.io/valeford-app/valeford-web \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
