name: Deploy static export to static-site branch

on:
  push:
    branches: [main]

permissions:
    contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build & export
        run: npm run build
        env:
          NEXT_PUBLIC_ASSET_PREFIX: /web

      - name: Create CNAME file
        run: echo 'valeford.de' > ./out/CNAME

      - name: Deploy to static-site branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: static-site
